[tool.mypy]
files = "degirum_tools,test"
exclude = ["temp", "setup.py"]
warn_unused_configs = true
ignore_missing_imports = true
check_untyped_defs = true
explicit_package_bases = true
warn_unreachable = false

